package fri.music.instrument.wave;

import java.net.URL;
import fri.music.HtmlResources;

public interface HelpForDifferenceToneForIntervalsPiano
{
    String TITLE = "See and Hear Difference-Tones Generated by Various Intervals";
    URL URL = HtmlResources.getUrl(HelpForDifferenceToneForIntervalsPiano.class);
}
