package fri.music.instrument.wave;

interface HelpForPianoSettings
{
    String HTML = """
<html>
<head></head>
<body>

<h1>Piano Controls</h1>
<p>
  The controls on top of the user-interface affect the piano on bottom.
</p>

<h3>On/Off Switch</h3>
<p>
With this switch you can turn off sound while the piano is playing, 
be it because you click a piano key or the notes-player is running.
It's also an emergency switch when something goes wrong with the 
computer's sound resources, but hopefully you won't need it ever.
</p>

<h3>Tunings</h3>
<p>
There are 8 different (hardcoded) tunings for 12-tone scales (which I took from Wikipedia).
Mind that the application is not equipped for others than 12-tone scales.
</p>
<p>
The <i>EqualTemperament</i> is a modern neutral tuning that tries
to balance all dissonances as good as possible by establishing the
same distance (100 <i>cent</>) between all semitones.
This gives a lot of freedom to modulations and chord progressions.
Try out a C-major scale, you will see that
all difference-tone interval-lists of <i>EqualTemperament</i>
have the same structure.
</p>
<p>
Most of the other tunings are <i>JustIntonation</i> scales. 
These have variable distances between their semitones.
They focus on the good sound of 7-tone "modal" scales, 
that means there should be less beatings (vibrations, discords) in a polyphonic
performance with <i>JustIntonation</i>.
The word "limit" refers to prime numbers used in the tuning's frequency calculations.
Most of the <i>JustIntonation</i> difference-tone interval-lists have different structures.
</p>
<p>
The <i>Pythagorean</i> is the oldest known mathematically founded tuning
of the Western world. It has been abandoned in the 16th century 
due to its strong beatings.
</p>
<p>
The <i>Harmonic Series</i> is a tuning derived from overtone analysis.
Mind that some of its tones can not be generated by difference-tone intervals:
if you load a C-major scale into the text-area, 
you will see that its "F" and "A" interval-lists are empty (deviation 76 %).
</p>

<h3>Deviation Tolerance</h3>
<p>
If you calculate difference-tones from the frequencies of two higher notes, 
you will see that the difference-tone's frequency mostly does not match
a scale tone. The deviation tolerance defines how much the difference-tone 
is allowed to be away from a regular scale tone.
If you have a deviation of 100 %, the difference tone is allowed to be
exactly in the middle between two semitones, which makes it very ambiguous. 
Therefore the maximum deviation you can configure here is 90 %.
A good average value for all tunings is 76 %, this enables also tritone intervals
for <i>JustIntonation</i>.
</p>
<p>
Try out a C-major scale, then reduce the deviation to zero.
You will see that the difference-tone intervals lists get empty
for <i>EqualTemperament</i>, and will be quite reduced for <i>JustIntonation</i>.
</p>
<p>
Try more things. For example, put deviation back to 76 %, set <i>JustIntonation</i>,
then click "C4" and slowly reduce deviation down to zero.
You will see that all the intervals from minor third up to major sixth remain
in the difference-tone intervals list of "C4". That means the tuning is very clean,
in other words, it generates nearly no beatings when used polyhonically.
</p>

<h3>Narrowest Interval</h3>
<p>
The closer the tones of an interval are together, the deeper their difference-tone will become.
If you have a major second interval, e.g. "[C6 D6]", the differece-tone will be 3 octaves lower on "C3".
</p>
<p>
If you reduce deviation, you will see that just <i>fifth</i> and <i>fourth</i> will remain as
difference-tone intervals. All others are fuzzy and imprecise.
Thus it makes few sense to allow intervals smaller than minor-third. 
</p>
<p>
Try to switch to <i>Limit-5-Symmetric-1 JustIntonation</i> (76 % deviation) and configure 
major-second as narrowest interval. Click the "C3" piano key.
In the interval-list below, you will see that both the intervals
"[C6 D6]" and "[D6 E6]" generate "C3", which makes major-second very ambiguous.
</p>

<h3>Widest Interval</h3>
<p>
The wider the tones of an interval are apart, the higher their difference-tone will become.
If you have an octave, the difference-tone will be identical with the lower tone and thus disappear.
Thus it makes few sense to allow intervals greater than major-sixth. 
</p>

<h3>Wave Form</h3>
<p>
The piano can be played with different sounds.
For hearing difference-tones, the best will be the "Sine" wave form,
but "Triangle" is also quite good.
The less overtones the sound has (sine-wave is the purest), 
the better you will hear difference-tones.
</p>

<h3>Amplitude</h3>
<p>
The volume control (loudness) is called "Amplitude" because the sound of the piano
is created by a wave-generator, not a MIDI-synthesizer.
Reason for the wave-generator is, you cannot tune a Java MIDI-synthesizer,
its tuning is fixed to equal-temperament, but here different tunings are needed
to explore the nature of difference-tones.
</p>

</body>
</html>
""";
}